[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
hook_source = '''
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary='/usr/local/opt/rust/bin/racer'
    let g:deoplete#sources#rust#rust_source_path='/usr/local/opt/rust/share/rust/rust_src/'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
'''
